list= [17, 38, 10, 25, 72]
list.sort()
print(list)
list.append(12)
print(list)
list.reverse()
print(list)
print(list.index(17))
list.pop(2)
print(list[2:4])
print(list[:2])
print(list[3:])
print(list[:])
print(list[-1])